# 5
# Usado para armazenar dados secretos
# seguir para inserir no deployment e refinar o arquivo de secret amanha 

apiVersion:  v1
kind: Secret
metadata:
  name: db-secret-1
type: Opaque
data:
    senha: MTIzNDU2 # 123456 em base64
    usuario: YWRtaW4=  # admin em base64
  